### ISSUE TITLE
Button is not rendered correctly

### ISSUE THREAD

**Issue by ammarahm-ed** [triniwiz/nativescript-mason#13]
```js
   <flex
      style={{
        backgroundColor: "#808080",
        width:400
      }}
    >
      <button
        style={{
          height: 50,
          width:300
        }}
        text="Hello world"
      />
    </flex>
```
The set width of the button is not reflected in rendered button.

![Screenshot 2023-02-06 at 10 40 38 PM](https://user-images.githubusercontent.com/40239442/217045053-789666eb-f6f0-4e2d-bbee-7df97f3dbe59.png)

The best i could get was this:
```
  <flex
      style={{
        backgroundColor: "#808080",
        width:'100%'
      }}
    >
      <button
        style={{
          height: 50,
          width:'100%',
          minWidth:200
        }}
        text="Hello world"
      />
    </flex>
```
Setting minWidth makes the size of button change, width property has no affect.
![Screenshot 2023-02-06 at 10 43 39 PM](https://user-images.githubusercontent.com/40239442/217045700-fc9e623d-3e31-451d-9115-0415e6ba9e7b.png)
Also for some reason the alignment of button is not correct. It's left aligned.

After setting width/minWidth as same value the text sticks to the top edge of the button

```
<button
        style={{
          height: 50,
          width:200,
          minWidth:200,
          minHeight:50
        }}
        text="Hello world"
      />
```
![Screenshot 2023-02-06 at 10 45 27 PM](https://user-images.githubusercontent.com/40239442/217046066-b48e6a5c-5a3d-49f6-b333-4a726b6b9855.png)

**Comment by triniwiz** [comment]
This also works in vanilla

**Comment by ammarahm-ed** [comment]
That's strange. I'll check, maybe something else is missing. because it's working fine for other layouts except mason.
